### ISSUE TITLE
setup.py issues with darwin

### ISSUE THREAD

**Issue by SkyLeach** [libyal/libvmdk#12]
```
| ~/src/libvmdk @ MAGREGOR-M-W0XX (magregor)
| => python2.7 setup.py install
running install
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 324, in <module>
    data_files=[(PYTHON_LIBRARY_DIRECTORY, LIBRARY_DATA_FILES)],
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 69, in run
    output = self._RunCommand(command)
  File "setup.py", line 49, in _RunCommand
    command, error))
RuntimeError: Running: sh configure --help failed with error:
sh: configure: No such file or directory
.
```

There are a couple of reasons for this.  First, autopoint is required to update the macros for autotools before the configure script will be created.  The only homebrew package available that has autopoint is gettext, and gettext conflicts with the apple-provided gittext so it doesn't get autolinked.  (see: http://arielvb.readthedocs.io/en/latest/docs/mac/commandline.html#gettext)

I am workingn on a pull request for this and will update this issue with the pull request once I finish.

**Comment by SkyLeach** [comment]
PR #13 
however glibc configure scripts aren't being found.

Advice appreciated.

**Comment by joachimmetz** [comment]
Have a look at https://github.com/libyal/libvmdk/wiki/Building#read-first

you're using a developer release not a distribution release.

**Comment by SkyLeach** [comment]
I realize it's homebrew-centric, but since the vast majority of people who use Mac use homebrew and since it doesn't break any other builds (easy to tweak it to check for homebrew or take a flag) I would think it would be useful anyhow.

Not trying to be a pain, just thought it might be a bit less painful.

**Comment by joachimmetz** [comment]
Don't get me wrong I appreciate the gesture. However there is a difference between development releases and distribution releases for a reason. Libvmdk is dependent on various other libraries of which their source and testing done as part of different (libyal) projects. This is less painful from the maintainer side (me).

There also can be various issues with the autotools on different platforms, hence I'm hesitant to have non-developers / non-maintainers directly use it and have to troubleshoot these issues. Distribution packages are designed to be self contained.

Also libvmdk-python distribution packages can be found on pypi (https://pypi.python.org/pypi/libvmdk-python/) if you really want it easy.

**Comment by SkyLeach** [comment]
@joachimmetz 👍 
bad habbit mine, testing modules from source before testing pypi
